// <auto-generated />
using BallroomWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BallroomWebApp.Migrations
{
    [DbContext(typeof(MvcDanceContext))]
    partial class MvcDanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("BallroomWebApp.Models.Dance", b =>
                {
                    b.Property<int>("DanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .HasColumnType("TEXT");

                    b.HasKey("DanceId");

                    b.ToTable("Dance");
                });

            modelBuilder.Entity("BallroomWebApp.Models.DanceMove", b =>
                {
                    b.Property<int>("DanceMoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DanceVideoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyllabusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DanceMoveId");

                    b.HasIndex("DanceVideoId");

                    b.HasIndex("SyllabusId");

                    b.ToTable("DanceMove");
                });

            modelBuilder.Entity("BallroomWebApp.Models.DanceVideo", b =>
                {
                    b.Property<int>("DanceVideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("DanceVideoId");

                    b.ToTable("DanceVideo");
                });

            modelBuilder.Entity("BallroomWebApp.Models.Syllabus", b =>
                {
                    b.Property<int>("SyllabusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("SyllabusId");

                    b.HasIndex("DanceId");

                    b.ToTable("Syllabus");
                });

            modelBuilder.Entity("BallroomWebApp.Models.DanceMove", b =>
                {
                    b.HasOne("BallroomWebApp.Models.DanceVideo", "Video")
                        .WithMany()
                        .HasForeignKey("DanceVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallroomWebApp.Models.Syllabus", "Syllabus")
                        .WithMany()
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BallroomWebApp.Models.Syllabus", b =>
                {
                    b.HasOne("BallroomWebApp.Models.Dance", "Dance")
                        .WithMany()
                        .HasForeignKey("DanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
